/*
* Generated file
*
* Generated from: yang module name: pcmm-service-impl yang module local name: pcmm-service
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Aug 11 20:15:05 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.pcmm_service.impl;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:config:pcmm-service:impl?revision=2014-08-10)pcmm-service", osgiRegistrationType = org.opendaylight.controller.org.pcmm.api.PcmmService.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:pcmm-service:impl", revision = "2014-08-10", localName = "pcmm-service")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:pcmm-service:impl", revision = "2014-08-10", name = "pcmm-service-impl")

public interface PcmmServiceServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
